# Required to connect to your outgoing mail server. Example for using gmail:
# gmail
SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587
USERNAME: benjamin.heasly@gmail.com
PASSWORD:

TIMEZONE: 'US/Eastern'

PARTICIPANTS:
  - Joe & Carolyn <caroalic@maine.rr.com>
  - Nora of the North & Sebastian <lizheasly@gmail.com>
  - Daniel <benjamin.heasly@gmail.com>
  - Leander Abdallah <rheasly@gmail.com>
  - Jesse & KT <jheasly@gmail.com>
  - Paul <paulheasly@gmail.com>
  - Leah & Phil <leahheasly@gmail.com>
  - Sarah <sjheasly@gmail.com>
  - Anna <annaheasly@gmail.com>
  - The McLeans <DLBullen@aol.com>
  - The Bostonians (Karen & Alex) <karen.l.bippus@gmail.com>
  - Elizabeth <emily.c.bullen@gmail.com>
  - Lucy <lucy.d.bullen@gmail.com>
  - Patrice <phheasly@gmail.com>
  - Hannah & Nora of the South & Jack & Amelia <Christopher.Heasly@gmail.com>
  - Kathryn <kpheasly@gmail.com>
  - Carolyn Luisa <clheasly@gmail.com>
  - The Yardleys (Anne & Richard) <aheasly@gmail.com>
  - Calvin <calhodge1@gmail.com>
  - Elliot <elliot.hodge@gmail.com>
  - John <jheasly@earthlink.net>
  - Patsy <paheasly@gmail.com>

# Warning -- if you mess this up you could get an infinite loop
DONT-PAIR:
  - John, Elizabeth
  - Paul, Sarah, Anna, Patsy, Leah & Phil
  - Joe & Carolyn, Nora of the North & Sebastian, Daniel
  - The Bostonians (Karen & Alex), Elizabeth, Lucy, The McLeans
  - Hannah & Nora of the South & Jack & Amelia, Carolyn Luisa, Patrice, Kathryn
  - The Yardleys (Anne & Richard), Calvin, Elliot
  - Leander Abdallah, Joe & Carolyn

# From address should be the organizer in case participants have any questions
FROM: Ensemble Borealis <benjamin.heasly@gmail.com>

# Both SUBJECT and MESSAGE can include variable substitution for the 
# "santa" and "santee"
SUBJECT: Ensemble Borealis presents -- your 2023 CONFIRMATION email
MESSAGE: |
  Dear {santa},

  Love and hugs to you, again!

  This is to confirm that you're shopping for {santee} in 2023.

  (or in a couple cases, to tell you who you're really shopping for)

  Have a good one!

  Love,

    -- All of us here at Ensemble Borealis
