# Required to connect to your outgoing mail server. Example for using gmail:
# gmail
SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587
USERNAME: benjamin.heasly@gmail.com
PASSWORD: pibfmhqddlzewehf

TIMEZONE: 'US/Eastern'

PARTICIPANTS:
  - Joe & Carolyn <caroalic@maine.rr.com>
  - Nora of the North & Sebastian <lizheasly@gmail.com>
  - Daniel <benjamin.heasly@gmail.com>
  - Rachel & Mark <rheasly@gmail.com>
  - Jesse & KT <jheasly@gmail.com>
  - Paul <paulheasly@gmail.com>
  - Leah & Phil <leahheasly@gmail.com>
  - Sarah <sjheasly@gmail.com>
  - Anna <annaheasly@gmail.com>
  - The McLeans <DLBullen@aol.com>
  - The Chicagoans (Karen & Alex) <karen.l.bullen@gmail.com>
  - Elizabeth <emily.c.bullen@gmail.com>
  - Lucy <lucy.d.bullen@gmail.com>
  - Patrice <phheasly@gmail.com>
  - Hannah & Nora of the South & Jack & Amelia <Christopher.Heasly@gmail.com>
  - Kathryn <kpheasly@gmail.com>
  - Carolyn Luisa <clheasly@gmail.com>
  - The Yardleys (Anne & Richard) <aheasly@gmail.com>
  - Calvin <calhodge1@gmail.com>
  - Elliot <elliot.hodge@gmail.com>
  - John <jheasly@earthlink.net>
  - Patsy <paheasly@gmail.com>

# Warning -- if you mess this up you could get an infinite loop
DONT-PAIR:
  - Paul, Sarah, Anna, Patsy, Leah & Phil
  - Joe & Carolyn, Nora of the North & Sebastian, Daniel
  - The Chicagoans (Karen & Alex), Elizabeth, Lucy, The McLeans
  - Hannah & Nora of the South & Jack & Amelia, Carolyn Luisa, Patrice, Kathryn
  - The Yardleys (Anne & Richard), Calvin, Elliot

# From address should be the organizer in case participants have any questions
FROM: Your Northern Lights of Christmas <benjamin.heasly@gmail.com>

# Both SUBJECT and MESSAGE can include variable substitution for the 
# "santa" and "santee"
SUBJECT: Your 2022 Northern Lights of Christmas of Joy
MESSAGE: |
  Dear {santa},

  Greetings and hugs!

  Assuming participation is the same as *last* year, *this* year you are shopping for {santee}!

  If you want to change your Consortium participation this year, please reply to this by November 11th.  We can adjust the pairings and re-send the emails on or around the 13th.  And that's it!

  Ho Ho Ho!

  Beep-beep-beeeep and all that.

  The spending limit is $30.00. (And it doesn't even have to be a purchase; it can be a hand-made item or a gift certificate for a hand-made item or whatever ... )

  This message was automagically generated by me, a computer.  Nothing could prossibly go wrong!

  Thank you.

    -- Computer

